### PR TITLE
Add variables to set artefacts to produce.

### PR DESCRIPTION
**Pull request by sballari**
The following variables can be set either to false or true:

ECLAIR_metrics_tab      metrics in spreadsheet format
ECLAIR_reports_tab      findings in spreadsheet format
ECLAIR_summary_txt      summary report in plain textual format
ECLAIR_summary_doc      summary report in DOC format
ECLAIR_summary_odt      summary report in ODT format
ECLAIR_full_txt_areas   enable/disable detailed reports in txt format
ECLAIR_full_txt         rich/detailed report in plain textual format
ECLAIR_full_doc_areas   enable/disable detailed reports in ODT/DOC format
ECLAIR_full_doc         rich/detailed report in DOC format
ECLAIR_full_odt         rich/detailed report in ODT format

### CODE REVIEW

**Comment by sballari** [comment]
This PR includes also a change to add an analysis summary in the cmake log

**Comment by simhein** [comment]
@sballari would it possible to sign-off your commit? after that I can prepare the overall PR to get our changes upstream :) Thanks

**Comment by sballari** [comment]
@simhein I added the requested signed-offs, this first iteration should be ready to be submitted.

**Comment by simhein** [comment]
@sballari I cherry picked the commits from your branch into mine due to conflicts and rebasing. I will close this PR for now

**Pull request closed without merging**
